### ISSUE TITLE
gradio版本是不是有问题呀

### ISSUE THREAD

**Issue by Nagin-Kim** [X-D-Lab/MindChat#12]
ab/flash-attention
Loading checkpoint shards: 100%|████████████████████████████████████████████████████| 8/8 [00:12<00:00,  1.61s/it]
Traceback (most recent call last):
  File "/data/code/MindChat/webui_demo.py", line 58, in <module>
    demo = gr.ChatInterface(predict,
  File "/data/jt_conda/mindchat/lib/python3.9/site-packages/gradio/chat_interface.py", line 273, in __init__
    client_utils.synchronize_async(self.examples_handler.cache)
AttributeError: 'ChatInterface' object has no attribute 'examples_handler'

**Comment by thomas-yanxin** [comment]
已经修复，指定gradio==3.37.0即可，后续我们更新一下webui.py适应新版本的gradio。

感谢指出！
