### ISSUE TITLE
在qwen里运行webdemo报错了

### ISSUE THREAD

**Issue by TigerHH6866** [X-D-Lab/MindChat#8]
(my-env) root@autodl-container-072d119c3c-81e484cb:~/autodl-tmp/Qwen# python web_demo.py
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.21s/it]
WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu.
Running on local URL:  http://127.0.0.1:6006

To create a public link, set `share=True` in `launch()`.
User: nihao
Traceback (most recent call last):
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/root/autodl-tmp/Qwen/web_demo.py", line 124, in predict
    for response in model.chat_stream(tokenizer, _query, history=_task_history, generation_config=config):
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'QWenLMHeadModel' object has no attribute 'chat_stream'

**Comment by thomas-yanxin** [comment]
这好像不是本项目提供的[脚本](https://github.com/X-D-Lab/MindChat/blob/main/webui_demo.py)。

**Comment by thomas-yanxin** [comment]
你可以暂时用千问官方的[modeling_qwen.py](https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/modeling_qwen.py)替换MindChat模型中的modeling_qwen.py，后面我们更新一下。
